### ISSUE TITLE
Why not use Uri.parse or String instead of OkHttp?

### ISSUE THREAD

**Issue by piaci** [chimbori/crux#22]
okhttp must be implemented in gradle for the only reason to pass HttpUrl object to the constructor?
wouldn't it be simplier to use Uri.parse or just a simple string?

**Comment by chimbori** [comment]
`java.net.URI` and `java.net.URL` have significant issues, see here: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/#why-another-url-model

The cost of the OkHttp dependency is well worth it to ensure correctness and so we don’t have to reimplement a URI parser ourselves.

**Comment by piaci** [comment]
while I do understand the necesity of oktthp in this case, I still don't see why the user must implement it as well.
passing a string to constructor would not require to add it to gradle, since it's already added to crux.

**Comment by chimbori** [comment]
It’s a cleaner API if you are passing in an already-parsed `HttpUrl` instead of random strings. 

Plus, in our apps, we pass around `HttpUrl`s anyway, so converting that to a string to pass to Crux is wasted effort.

If your concern is about having to depend on OkHttp in your own app, then we can change this to be `api()` rather than `implementation()` so you don’t have to import it yourself.

**Comment by piaci** [comment]
thank you!

**Comment by DHosseiny** [comment]
> It’s a cleaner API if you are passing in an already-parsed `HttpUrl` instead of random strings.
> 
> Plus, in our apps, we pass around `HttpUrl`s anyway, so converting that to a string to pass to Crux is wasted effort.
> 
> If your concern is about having to depend on OkHttp in your own app, then we can change this to be `api()` rather than `implementation()` so you don’t have to import it yourself.

It is a good idea because now crux is plug and play instead of adding more dependencies that may you don't know why you are adding. thanks
